version: '3.8'

services:
  nexstay-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: nexstay-app
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID}
      - AWS_COGNITO_AUTHORITY=${AWS_COGNITO_AUTHORITY}

  database:
    image: postgres:16.2
    container_name: nexstay_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
